// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"time"
)

type Querier interface {
	//CreateStream
	//
	//  INSERT INTO streams(id, updated)
	//  VALUES ($1, $2) ON CONFLICT (id) DO NOTHING
	CreateStream(ctx context.Context, arg CreateStreamParams) error
	//GetOnlineStreams
	//
	//  SELECT id, updated, url, online, player_names
	//  FROM streams
	//  WHERE online = true
	GetOnlineStreams(ctx context.Context) ([]Stream, error)
	//GetSchemaVersion
	//
	//  SELECT version
	//  FROM schema_version
	GetSchemaVersion(ctx context.Context) (int32, error)
	//SearchStreamsByNickname
	//
	//  SELECT id, updated, url, online, player_names
	//  FROM streams
	//  WHERE online = true
	//    AND EXISTS (SELECT 1
	//                FROM unnest(player_names) AS nickname
	//                WHERE levenshtein(lower(nickname), lower($1::VARCHAR(255))) < $2::INTEGER OR
	//                                                                                            lower(nickname) LIKE '%' ||
	//                                                                                                                 lower($1::VARCHAR(255)) ||
	//                                                                                                                 '%')
	//    LIMIT $3::INTEGER
	SearchStreamsByNickname(ctx context.Context, arg SearchStreamsByNicknameParams) ([]Stream, error)
	//SetSchemaVersion
	//
	//  UPDATE schema_version
	//  SET version = $1
	SetSchemaVersion(ctx context.Context, version int32) error
	//SetStreamOnline
	//
	//  UPDATE streams
	//  SET online  = true,
	//      updated = $2
	//  WHERE id = $1
	SetStreamOnline(ctx context.Context, arg SetStreamOnlineParams) error
	//UpdateStaleStreams
	//
	//  UPDATE streams
	//  SET online = false
	//  WHERE updated < $1
	UpdateStaleStreams(ctx context.Context, updated time.Time) error
	//UpdateStreamData
	//
	//  UPDATE streams
	//  SET player_names = $2
	//  WHERE id = $1
	UpdateStreamData(ctx context.Context, arg UpdateStreamDataParams) error
	//UpdateStreamUrl
	//
	//  UPDATE streams
	//  SET url = $2
	//  WHERE id = $1
	UpdateStreamUrl(ctx context.Context, arg UpdateStreamUrlParams) error
}

var _ Querier = (*Queries)(nil)
