// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
)

// General defines model for General.
type General struct {
	Error      bool   `json:"error"`
	Msg        string `json:"msg"`
	StatusCode int    `json:"statusCode,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	BuildDate string `json:"buildDate"`
	Version   string `json:"version"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Query string `json:"query"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Data []Stream `json:"data"`
}

// Stream defines model for Stream.
type Stream struct {
	Name      string   `json:"name"`
	Nicknames []string `json:"nicknames"`
}

// SearchPlayersJSONRequestBody defines body for SearchPlayers for application/json ContentType.
type SearchPlayersJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	HealthCheck(c *fiber.Ctx) error
	// Search players
	// (POST /search)
	SearchPlayers(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *fiber.Ctx) error {

	return siw.Handler.HealthCheck(c)
}

// SearchPlayers operation middleware
func (siw *ServerInterfaceWrapper) SearchPlayers(c *fiber.Ctx) error {

	return siw.Handler.SearchPlayers(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)

	router.Post(options.BaseURL+"/search", wrapper.SearchPlayers)

}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(ctx *fiber.Ctx) error
}

type HealthCheck200JSONResponse HealthResponse

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type HealthCheckdefaultJSONResponse struct {
	Body       General
	StatusCode int
}

func (response HealthCheckdefaultJSONResponse) VisitHealthCheckResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(response.StatusCode)

	return ctx.JSON(&response.Body)
}

type SearchPlayersRequestObject struct {
	Body *SearchPlayersJSONRequestBody
}

type SearchPlayersResponseObject interface {
	VisitSearchPlayersResponse(ctx *fiber.Ctx) error
}

type SearchPlayers200JSONResponse SearchResponse

func (response SearchPlayers200JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type SearchPlayers400JSONResponse General

func (response SearchPlayers400JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type SearchPlayers401JSONResponse General

func (response SearchPlayers401JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type SearchPlayers403JSONResponse General

func (response SearchPlayers403JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type SearchPlayers404JSONResponse General

func (response SearchPlayers404JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type SearchPlayers500JSONResponse General

func (response SearchPlayers500JSONResponse) VisitSearchPlayersResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /healthz)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Search players
	// (POST /search)
	SearchPlayers(ctx context.Context, request SearchPlayersRequestObject) (SearchPlayersResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(ctx *fiber.Ctx) error {
	var request HealthCheckRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx.UserContext(), request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchPlayers operation middleware
func (sh *strictHandler) SearchPlayers(ctx *fiber.Ctx) error {
	var request SearchPlayersRequestObject

	var body SearchPlayersJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPlayers(ctx.UserContext(), request.(SearchPlayersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPlayers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchPlayersResponseObject); ok {
		if err := validResponse.VisitSearchPlayersResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQVPbPBD9K579vmMah0IvvhVaWnroMKSdHhgOiryJBbYkViumhvF/70hKIIndcElz",
	"4hSNdvXe29VbxU8gTWONRs0OiidwssJGxOUX1EiiDktLxiKxwhhAIkNhwa1FKGBmTI1CQzeCxi3WAo5J",
	"6UXYdyzYuzNT4lpYacYFEozg9zvTKMbGcgsFk8euGwHhvVeEJRTXS8qEv4F2M1qhmdktSg5kX1HUXF2h",
	"s0Y77OufeVWXnwTjoNQHJKeMHohtaVoljtYAh+RMUZCsrvDeo+O+mnuP1L7OltJ24f+t3FKwCL+hwXHj",
	"f8I5FPBf/nL1+fLe8ykTiibALnkEkWh7aiLmoJh0vidCi2a43VrJuxB0GxJ7aTvVRPB1qL6y4EGUnhS3",
	"01Bq4rtEapQLt5iMgYKQzg01gqGAb79+BLPF9GDzGIVn6IrZQheQlZ6bcF4azULyS71QtRZpbqR3sQjF",
	"9eZu9vHyAtY8B0fjyXgSco1FLayCAo7Hk/EJjMAKrqLMvIoGfwzrBUa60GrByuiLEorlAJxVKO8gdCo5",
	"I559P5mslKKOR4W1tZLxcH7rkvGTG17zytacxVaU6CQpy6maKdKDkpgplyXNLcScufA1703H6qHaLcDr",
	"ZwnBDL5pRJi7ZbMyGbsVQrmLAxU9bNxAe9PAXdaiRXKQrIiOT03Z7q2mzUej23R8fCH/4cVuvShDffVS",
	"ooumPtkj8Y6bPBVl9tyOwHp0CNafWniuDKlHLBPt8SFozw3NVFmiTpwnh+D8bjg7N17HOj8c5lIvNCNp",
	"UWdhTpGyz/FvfnM+kxkzuxy3Lj3lId1Bcf20hZjeU081FJA/HEF3E74u4udDHJM3t765dd9u7f4EAAD/",
	"/y7p5ItFCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
